version: '3.3'

services:

  mysql:
    container_name: starterkitdb
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.20
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  server:
    image: starterkitapi
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "8080:8080"
    # Override the env according to your target environment, we can utilize .env to store env vars in file
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DSN=${DB_USER}:${DB_PASSWORD}@(mysql:3306)/${DB_NAME}?parseTime=true&multiStatements=true
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - mysql
    command: sh -c "/wait && /app/entrypoint.sh"
